<?php
//http://sailplay.ru/api/v1/login/?store_department_key=66016604&store_department_id=621&pin_code=7915
?>

<script charset="utf-8" type="text/javascript">
	var _publicKey = "none";
	

	if(document.getElementById("publicKey"))
		_publicKey = document.getElementById("publicKey").value;
	
	console.log(_publicKey);
	var _auth_hash = '<?php echo $this->getAuthash() ?>';
	var _sp_options = {
		publicKey: _publicKey,
		partnerId: "537",
		position: ["top", "right"],
		authHash: _auth_hash,
		notifications: {
			enabled: true,
			skin: {type: 'horizontal', position: ['bottom', 'right']}
		}
	};
	(function() {
		var sp = document.createElement("script");
		sp.type = "text/javascript"; sp.async = true; sp.charset = "utf-8";
		sp.src = ("https:" == document.location.protocol ? "https://" : "http://") +
			"sailplay.ru/popup-sdk/js/sailplay/537/";
		var scr = document.getElementsByTagName("script")[0]; scr.parentNode.insertBefore(sp, scr);
	})();
  
	function setCookie(cname,cvalue,exdays)
	{
		var d = new Date();
		d.setTime(d.getTime()+(exdays*24*60*60*1000));
		var expires = "expires="+d.toGMTString();
		document.cookie = cname + "=" + cvalue + "; " + expires;
	}
	
	function getCookie(cname)
	{
		var name = cname + "=";
		var ca = document.cookie.split(';');
		for(var i=0; i<ca.length; i++) 
		{
			var c = ca[i].trim();
			if (c.indexOf(name)==0) return c.substring(name.length,c.length);
		}
		return "";
	}
	
	var sailplay_auth_hash =  getCookie('sailplay_auth_hash');
	console.log("sailplay_auth_hash:" + sailplay_auth_hash);
	
	var isloggedin = <?php echo $this->isLoggedIn() ?>;
	
	document.observe('dom:loaded', function(){
		if(isloggedin==true){
			if(!sailplay_auth_hash){
			
				var url = '<?php echo Mage::getBaseUrl('web') ?>sailplay/index/getauthash';				
				 
				var request = new Ajax.Request(url,{
                    method: 'get',
                    onSuccess: function(response){	
						console.log(response.responseText);
						setCookie('sailplay_auth_hash', response.responseText, 10)
					}
				});
			}			
		}
		else
			if(sailplay_auth_hash!='')			
				setCookie('sailplay_auth_hash', '', 1)
			
	});
	
</script>


<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>

<script type="text/javascript">
	jQuery.noConflict();
	
  jQuery(function( $ ){
    window.SPready = function(SP) {
      $('input[name=origin-user-id-enabled]').change(function(){
        if ($(this).is(":checked")) {
          $('.form-group.origin-user-id').fadeIn('fast');
        }
        else {
          $('.form-group.origin-user-id').fadeOut('fast');
        }
      });

      $('form.user-points').submit(function(e) {
        e.preventDefault();
        SP.api.getUserPoints({
          originUserId: $('#origin-user-id').val(),
          callback: function(data) {
            $('pre.user-points-result').text(JSON.stringify(data, undefined, 2));
          }
        });
      });

      $('.open-popup').click(function() {
        SP.showPopup();
      });

     $('select[name=target]').change(function() {

       if ($(this).val() == 'gift') {
         $('.gift-sku').slideToggle();
       }
       else {
         $('.gift-sku').hide();
       }
     });

      $('.open-popup-on-target').click(function() {
        SP.showPopup({
          openReload: true,
          openTo: {
            target: $('select[name=target]').find('option:selected').val(),
            giftSku: $('input[name=gift-sku]').val()
          }
        });
      });
	  


      SP.bindCallback('afterPopupClose', function() {
        console.log('Попап был закрыт');
      });

      SP.events.subscribe('gift', function(data) {
		console.log(data);
                location.reload();
      });
    }
  });
</script>
